### ISSUE TITLE
Suggestion: Make PrairieTest at least a little different from PrairieLearn

### ISSUE THREAD

**Issue by lkwagner** [PrairieLearn/PrairieTest-feedback#18]
Despite the importance of branding, the unobservant among us might have trouble distinguishing between these two systems at a glance, particularly when students post screenshots on certain help systems. I generally like the look of things, but it'd be great if there were maybe a slightly different color for the Test websites than the Learn websites so we know at a glance where we are.

**Comment by nwalters512** [comment]
We pretty deliberately rely on default [Bootstrap](https://getbootstrap.com/) for styles, so at this point we aren't going to add custom colors.
