### ISSUE TITLE
Logout of PrairieTest remains logged in on PrairieLearn

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieTest-feedback#20]
Our students use Google authn with their student accounts. Occasionally a student will not find their test, and it's because, by mistake, they have logged in using their Gmail instead. The problem is that if they logout on PrairieTest, when they login again they are not prompted for a new account. This, of course, may be a combination of things:
* Logging out on PrairieTest does not log out of PrairieLearn, so they'd need to log out there as well;
* Logging out of PT/PL does not log out of Google, so trying to use Google auth again may just assume the same login should be used instead.

Usually I just ask students to clear all cookies and that takes care of the problem (especially considering a CBTF-like environment where cookies are already limited so this operation is pretty quick).

For the first problem above, would logging out of PrairieTest also cause PrairieLearn to logout, or something similar, be something to be considered? Or at least a prompt on logout that also links to a "logout" URL in PrairieLearn?

For the second problem: this is probably a PrairieLearn thing rather than PrairieTest, so if you'd prefer I can have a separate issue there, but it seems like, according to [the OAuth documentation](https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters), it is possible to set `prompt=select_account` to force Google to show a page to select the account to be used, even if only one account is currently logged in. I'm wondering if this is something to be considered in this scenario.

**Comment by jonatanschroeder** [comment]
So this issue happened yesterday, before the latest deploy. I just went to test it again, and it seems that logout is now disabled. I imagine this is because auth is assumed to be taken from PrairieLearn. The problem is that, if I change auth in PrairieLearn, then PrairieTest will remain in the old auth/UID.

**Comment by jonatanschroeder** [comment]
> So this issue happened yesterday, before the latest deploy. I just went to test it again, and it seems that logout is now disabled. I imagine this is because auth is assumed to be taken from PrairieLearn. The problem is that, if I change auth in PrairieLearn, then PrairieTest will remain in the old auth/UID.

This particular issue is (presumably) resolved in PT #1109. The original issue persists.

**Comment by nwalters512** [comment]
This will be fixed by https://github.com/PrairieLearnInc/PrairieTest/pull/1110 / https://github.com/PrairieLearn/PrairieLearn/pull/7142.

**Comment by jonatanschroeder** [comment]
> This will be fixed by [PrairieLearnInc/PrairieTest#1110](https://github.com/PrairieLearnInc/PrairieTest/pull/1110) / [PrairieLearn/PrairieLearn#7142](https://github.com/PrairieLearn/PrairieLearn/pull/7142).

Since these two and https://github.com/PrairieLearn/PrairieLearn/pull/7138 are now all merged I'm closing this as resolved.

**Comment by nwalters512** [comment]
These changes should be deployed within the next week.
