### ISSUE TITLE
Bulk Edit Exam End Time

### ISSUE THREAD

**Issue by Jim-Sosnowski** [PrairieLearn/PrairieTest-feedback#26]
Under the "All Students" in an exam session page could you please add the ability bulk edit the exam end time.  Currently if a proctor needs to add to every student in the lab they have to manually edit each student's end time individually.  It would be very helpful and make my proctors very happy if they could do it all at once.  And save a lot of time for the proctors.

**Comment by steven-wolfman** [comment]
+1 to this. Any chance it's coming before mid-December? :)

**Comment by mwest1066** [comment]
This has now been implemented. There's a new "Extend time for all students" option under the "Actions for all students" menu on the session page.
