### ISSUE TITLE
Allow admins to create/edit/delete reservations for students

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieTest-feedback#41]
There are many reasons when it is necessary to create/edit/delete reservations for students in specific sessions. 

At minimum, testing centre admins should be able to do this, but I can imagine situations where it would be useful for "Exam Editors" and CBTF "Owners" to also have this privilege.

**Comment by Jim-Sosnowski** [comment]
I have it on my list that we have a similar issue open already (PT issue #953).

**Comment by nwalters512** [comment]
We've shipped this in a recent version of PrairieTest! This is currently available on the "exams" tab of a particular student. Click the exam, and you can then create/edit/delete a reservation for the student in that exam. We'll be bringing this same experience to other pages too. Please open new issues to share any additional feedback about this new feature.
