### ISSUE TITLE
Restrict sessions to only accept bookings from specific exams

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieTest-feedback#42]
At the UBC CBTF, we have two rooms dedicated to running CBTF exams. There are often cases when we want to have a session dedicated to a specific course or exam:

- "Strict-scheduled" quiz where a whole class does a midterm or a quiz in both of the CBTF rooms together. This is intended for courses who don't yet have enough randomization in their problem banks.

- "Assessment viewing facility" where students book 20-min sessions to view their assessments (from certain courses only) and we want to restrict some sessions specifically for this.

- Students doing make-up exams. At the moment, we reduce capacity of the session to "reserve" the spots from a general session, have the students show up and book a few mins before the session starts, or have a parallel course session where bookings can be created for students (this will likely be solved by #41)

- One particular graduate program is using the CBTF in a somewhat special way with slightly different proctoring rules, currently they're using course sessions but don't have the ability to check IDs using the card reader - they'd benefit from using CBTF sessions

At the moment, we have to create whole new CBTF sessions for each of those cases, or run them as course-sessions, which is confusing (high potential of double booking) or awkward (hard for admins to remember to schedule proctors and keep track of facility usage).

The MVP of this feature would be to lock an entire session to a specific exam so only students can only do that exam in the session. Later "nice to haves" would be to restrict specific seats within a session to a specific exam for greater flexibility.

**Comment by Jim-Sosnowski** [comment]
At UIUC this feature could also help with managing our remote testing site in Chicago.  Currently we create a separate center for those exams.

This would also help us to better manage / utilize our proctors.  Some of our proctors also have CBTF exams, but they are not allowed to proctor during their exam windows.  Restricting exams to specific rooms would allow proctors to continue working in rooms where their exam is not offered, avoiding conflicts of interest.

**Comment by mwest1066** [comment]
Implemented via exam/session "labels".
