### ISSUE TITLE
Weird defaults for new course session 

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieTest-feedback#46]
I'm creating course sessions on PT for my exam. It used to be the case that, when I create a second session, the default start time would be the same as the previous session, but this now defaults to 24 hours later. I think course sessions should default to the same time, as that is the most common scenario.

Also, the default for the session duration used to be 10 minutes more than the exam duration, but in this case it was exactly the exam duration.

**Comment by jonatanschroeder** [comment]
This is still biting me occasionally, and I almost misscheduled sessions because of it. Any chance of reviewing this soon?

**Comment by mwest1066** [comment]
Bumped it up my todo list.
