### ISSUE TITLE
Unknown event type in exam log

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieTest-feedback#48]
https://ca.prairietest.com/pt/course/961/staff/exam/3898/log lists entries for inserting seat holds, but this event does not have a proper formatting rule.

<img width="985" alt="image" src="https://github.com/PrairieLearn/PrairieTest-feedback/assets/1004907/dbd1a5e7-b569-4f39-8eb5-34185fe7f232">

**Comment by mwest1066** [comment]
Fixed -- PT no longer displays seat hold audit events (and it would correctly format them if they were displayed).
