### ISSUE TITLE
Feature request: password setting for exams

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieTest-feedback#56]
There are instances where it would be desirable to have an exam password. 

For example, I would like to use PrairieTest in unproctored mode for students who are going to take exams at the disability center. (In this scenario, I am using PrairieTest so that students will not be able to open other assessments in the course while in exam mode.)  I don't know who the proctor will be at the disability center, and they're not in PrairieTest. But, our disability center has the option for me to upload a paper exam that they print and give to the student. I used to upload a PDF with just the password in it, and they would print it and give it to the student at the start of the exam time.

**Comment by jonatanschroeder** [comment]
Does this solve your problem?

https://prairielearn.readthedocs.io/en/latest/accessControl/#passwords

**Comment by jonatanschroeder** [comment]
Just realized you asked about PrairieTest. In any case, I believe you can set it in PL regardless.

**Comment by ffund** [comment]
> Just realized you asked about PrairieTest. In any case, I believe you can set it in PL regardless.

I asked in Slack and was told not :shrug:

**Comment by jonatanschroeder** [comment]
I just tested this in my course and it worked. Basically you have an access rule like this:

```json
    {
      "mode": "Exam",
      "examUuid": "[YOUR UUID]",
      "password": "[YOUR PASSWORD]",
      "credit": 100
    }
```

**Comment by nwalters512** [comment]
Glad to see that this works! @ffund I'm going to close this issue, but if you have any trouble getting that to work, don't hesitate to reach out for help in any of the usual places.
