### ISSUE TITLE
Location descriptions

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieTest-feedback#60]
Add additional information about the location that is visible to students. The use case here would be to describe the location so that students could help make decisions on where to take their exam. (example: This lab is laptops only)

The description might also be useful for directions to the location.

Right now we tend to overload the location name with this information, but an info pop-up or link where the location name is displayed might give us more flexibility.

**Comment by nwalters512** [comment]
Location descriptions are now visible to students wherever they can view reservations. For instance, here it is on the student-facing reservation page:

<img width="515" alt="Screenshot 2024-08-20 at 16 21 09" src="https://github.com/user-attachments/assets/9181e87b-6c60-4e5f-8ddb-2d3184eeb3ae">
