### ISSUE TITLE
Override Time Default

### ISSUE THREAD

**Issue by Jim-Sosnowski** [PrairieLearn/PrairieTest-feedback#66]
When entering an override, the the start time is initially 0:01 but once you click to update the start date, the time defaults to 12:00.  It would be nice to have the start time default stay at 0:01.  I have faculty each semester who have to request additional overrides because they enter overrides not realizing that the start time changed.

**Comment by nwalters512** [comment]
This is tracked internally in https://github.com/PrairieLearnInc/PrairieTest/issues/1687.

**Comment by lkwagner** [comment]
It would be great if the default start time were 0:01 and the default end time were 23:59.

Adding to that, I found out that somehow it is easy to accidentally get the wrong year on the popup; and it allows you to enter an end date which is before the begin date. It might be easy enough to check that begin date < end date, which could avoid some of these errors.

**Comment by Jim-Sosnowski** [comment]
@lkwagner The end date being in the past is my fault.  When I created the exams in the CBTF I left "Use default dates for overrides" turned on instead of turning it off.  Those dates are all set in the past because I hadn't updated to make them relevant dates.  Sorry. Those are turned off now for your course so you at least shouldn't see override dates being in the past.

**Comment by nwalters512** [comment]
This was resolved in a recent release of PrairieTest.
