### ISSUE TITLE
Webhooks should be sent with `POST`

### ISSUE THREAD

**Issue by inducer** [PrairieLearn/PrairieTest-feedback#69]
PrairieTest sends its webhooks using the `GET` method.

This is not great for multiple reasons:

- HTTP specifies that payloads on `GET` are [not allowed to carry meaning](https://stackoverflow.com/a/983458), and implementations may discard them.
    - A possible example of that is that payloads get wiped out on redirect. (Yes, I just got bitten by that.)
- `GET` and `POST` have distinct caching semantics. While PT's webhooks are designed to be idempotent (:tada:), having them be randomly resubmitted by middleboxes is still not ideal.

**Comment by nwalters512** [comment]
Where/how are you seeing this? This is the (simplified) bit of code that sends webhook requests from PT:

```js
    const response = await fetch(webhook_delivery.url, {
      method: 'POST',
      headers: webhook_delivery.request_headers,
      body: webhook_delivery.request_body,
      signal: AbortSignal.timeout(config.webhookDeliveryTimeoutMilliseconds),
    });
```

And here's the relevant piece of documentation from https://us.prairietest.com/pt/docs/api/exam-access:

> PrairieTest sends webhook events to the LMS as POST requests with a JSON payload.

**Comment by inducer** [comment]
I think that was on my end; there was a redirect involved that may have turned the `POST` into a `GET`? I'm really not sure now. Forget I said anything for the moment, sorry about the noise.
