### ISSUE TITLE
Duplicate-display of assessment links in PT

### ISSUE THREAD

**Issue by moveisi** [PrairieLearn/PrairieTest-feedback#76]
For our midterm exam, we need to set a password exclusively for a group of students. So, we have two access rules: one for these selected students and another for the rest of the class, both using the same examUuid. However, this setup results in students seeing two links for the same exam in PrairieTest, which can be confusing during the exam. (Also [discussed in Slack](https://prairielearn.slack.com/archives/C02ECHUR48M/p1730905157251009).)

**Comment by nwalters512** [comment]
Screenshot for reference:

![Image](https://github.com/user-attachments/assets/a3d23eea-fca8-4e9c-8099-eb3f85e9c9bd)

**Comment by nwalters512** [comment]
This fix is now live in production.
